// STATUS: DIAMANT VGT SUPREME
'use strict';
let token = '';
let integrityStatus = null;
let backgroundRefreshRunning = false;
let backgroundRefreshTick = 0;
const id = value => document.getElementById(value);
const setText = (target, value) => { const node = id(target); if (node) node.textContent = String(value ?? '---'); };
const asArray = value => Array.isArray(value) ? value : [];
function requestID() { return globalThis.crypto.randomUUID(); }
async function api(path, options = {}) { const method = String(options.method || 'GET').toUpperCase(); const headers = new Headers({ Accept: 'application/json' }); if (token) headers.set('Authorization', `Bearer ${token}`); let body; if (Object.prototype.hasOwnProperty.call(options, 'json')) { headers.set('Content-Type', 'application/json'); body = JSON.stringify(options.json); } if (method !== 'GET' && method !== 'HEAD') headers.set('X-VGT-Request-ID', requestID()); const response = await fetch(path, { method, headers, body, credentials: 'same-origin', cache: 'no-store' }); const payload = await response.json().catch(() => ({ error: 'Ungültige Serverantwort' })); if (!response.ok) throw new Error(String(payload.error || `HTTP ${response.status}`)); return payload; }
async function exchangeBootstrap(code) { const response = await fetch('/api/v1/session/exchange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code }), credentials: 'same-origin', cache: 'no-store' }); if (!response.ok) throw new Error('Bootstrap-Sitzung wurde abgelehnt'); }
function toast(message, tone = '') { const node = document.createElement('div'); node.className = `toast ${tone}`.trim(); node.textContent = message; id('toasts').append(node); globalThis.setTimeout(() => node.remove(), 5000); }
function activate(view) { const allowed = new Set(['overview', 'audit', 'xdr', 'integrity', 'hardening', 'evidence', 'system']); const selected = allowed.has(view) ? view : 'overview'; document.querySelectorAll('[data-page]').forEach(page => { const active = page.dataset.page === selected; page.hidden = !active; page.classList.toggle('active', active); }); document.querySelectorAll('[data-view]').forEach(button => button.classList.toggle('active', button.dataset.view === selected)); const names = { overview: 'Übersicht', audit: 'SafetySys Audit', xdr: 'MHX XDR', integrity: 'Integrität', hardening: 'Härtung', evidence: 'Evidenz', system: 'System' }; setText('title', names[selected]); if (selected === 'evidence') loadEvidence().catch(handleError); if (selected === 'xdr') Promise.all([loadXdr(), loadMhx()]).catch(handleError); if (selected === 'integrity') loadIntegrity().catch(handleError); if (selected === 'hardening') loadHardening().catch(handleError); if (selected === 'audit') runAudit().catch(handleError); }
function metric(label, value, enabled) { const article = document.createElement('article'); article.className = `panel metric ${enabled ? 'on' : 'off'}`; const name = document.createElement('span'); const state = document.createElement('strong'); name.textContent = label; state.textContent = value; article.append(name, state); return article; }
function domainBar(label, active, total) { const row = document.createElement('div'); const heading = document.createElement('div'); const name = document.createElement('span'); const value = document.createElement('strong'); const track = document.createElement('div'); const fill = document.createElement('i'); const percent = total > 0 ? Math.round((active / total) * 100) : 0; name.textContent = label; value.textContent = `${percent}%`; heading.append(name, value); fill.style.width = `${percent}%`; track.append(fill); row.append(heading, track); return row; }
function renderStatus(status) { const p = status.protection || {}; const mhx = status.mhx || {}; const controls = [['DEFENDER ENGINE', p.Defender && p.DefenderService], ['ECHTZEITSCHUTZ', p.RealTimeProtection], ['VERHALTENSSCHUTZ', p.BehaviorProtection], ['CLOUDSCHUTZ', p.CloudProtection], ['NETZWERKSCHUTZ', p.NetworkProtection], ['MANIPULATIONSSCHUTZ', p.TamperProtection], ['FIREWALL', p.Firewall], ['SECURE BOOT', p.SecureBoot], ['TPM', p.Tpm], ['BITLOCKER', p.BitLocker], ['VBS', p.Vbs], ['WINDOWS UPDATE', p.WindowsUpdate]]; id('metrics').replaceChildren(...controls.map(([label, enabled]) => metric(label, enabled ? 'GESCHÜTZT' : 'PRÜFEN', enabled))); const score = Math.round((controls.filter(([, enabled]) => enabled).length / controls.length) * 100); const domainValues = [['ENDPOINT', [p.Defender && p.DefenderService, p.RealTimeProtection, p.BehaviorProtection, p.CloudProtection]], ['NETZWERK', [p.NetworkProtection, p.Firewall]], ['PLATTFORM', [p.SecureBoot, p.Tpm, p.Vbs, p.BitLocker]], ['REAKTION', [p.TamperProtection, p.IoavProtection, Number(p.AsrBlockRules) > 0, p.WindowsUpdate]]]; id('domainBars').replaceChildren(...domainValues.map(([label, values]) => domainBar(label, values.filter(Boolean).length, values.length))); id('postureRing').style.setProperty('--posture', `${score * 3.6}deg`); setText('postureRingValue', score); setText('postureVerdict', score >= 92 ? 'Souveräne Schutzlage' : score >= 67 ? 'Verstärkung erforderlich' : 'Kritische Exposition'); setText('postureDetail', `${controls.filter(([, enabled]) => enabled).length}/${controls.length} Schutzanker aktiv · MHX ${mhx.realtime ? 'online' : 'degraded'}.`); setText('dashMhxEvents', mhx.eventsEvaluated || 0); setText('dashMhxBlocked', mhx.eventsBlocked || 0); setText('dashIocs', mhx.threatIntelligence?.indicators || 0); setText('dashAsr', p.AsrBlockRules || 0); setText('score', score); setText('scoreTitle', score >= 92 ? 'Master-Schutzlage stabil' : score >= 67 ? 'Härtung empfohlen' : 'Kritische Schutzlücken erkannt'); setText('scoreText', `${controls.filter(([, enabled]) => enabled).length} von ${controls.length} Schutzankern aktiv · ${p.AsrRules || 0} ASR-Regeln, davon ${p.AsrBlockRules || 0} im Blockmodus · Defender-Signaturen ${p.SignatureAgeDays ?? '—'} Tag(e) alt.`); setText('platform', status.platform); setText('version', status.version); setText('sideState', 'MASTER CONTROL ONLINE'); setText('health', score >= 92 ? 'GESCHÜTZT' : 'AKTION ERFORDERLICH'); id('health').className = `badge ${score >= 92 ? 'good' : 'warn'}`; }
async function refresh() { renderStatus(await api('/api/v1/status')); }
function statusCell(value) { const cell = document.createElement('td'); const badge = document.createElement('b'); badge.className = `state ${String(value).toLowerCase()}`; badge.textContent = String(value); cell.append(badge); return cell; }
function renderAudit(result) { setText('auditPercent', `${Number(result.Percent || 0).toFixed(1)}%`); setText('auditPassed', result.Passed || 0); setText('auditFailed', result.Failed || 0); setText('auditWarnings', result.Warnings || 0); const rows = asArray(result.Checks).map(check => { const row = document.createElement('tr'); for (const value of [check.Id, check.Category, check.Title]) { const cell = document.createElement('td'); cell.textContent = String(value); row.append(cell); } row.append(statusCell(check.Status)); const comparison = document.createElement('td'); comparison.textContent = `${check.Actual || '—'} / ${check.Expected}`; row.append(comparison); return row; }); id('auditChecks').replaceChildren(...rows); }
function renderXdr(result) { setText('xdrCritical', result.Critical || 0); setText('xdrHigh', result.High || 0); setText('xdrMedium', result.Medium || 0); setText('xdrScanned', result.Scanned || 0); const rows = asArray(result.Findings).map(finding => { const row = document.createElement('tr'); row.append(statusCell(finding.Severity)); for (const value of [finding.Category, finding.Title, finding.Entity, finding.Evidence]) { const cell = document.createElement('td'); cell.textContent = String(value || '—'); row.append(cell); } row.title = finding.Description; return row; }); if (!rows.length) { const row = document.createElement('tr'); const cell = document.createElement('td'); cell.colSpan = 5; cell.textContent = 'Keine Findings im aktuellen Scan.'; row.append(cell); rows.push(row); } id('xdrFindings').replaceChildren(...rows); }
async function loadXdr() { renderXdr(await api('/api/v1/xdr/findings')); }
function mountSovereignAllowUI() { const modes = document.querySelector('.mhx-modes'); if (!modes) return; const panel = document.createElement('article'); panel.className = 'panel sovereign-allow'; const heading = document.createElement('div'); const eyebrow = document.createElement('p'); eyebrow.className = 'eyebrow'; eyebrow.textContent = 'OFFIZIELLE NETZWERKFREIGABEN'; const title = document.createElement('h3'); title.textContent = 'Signierte Anwendung freigeben'; const explanation = document.createElement('p'); explanation.textContent = 'Die Freigabe ist an Pfad, SHA-256 und Authenticode-Herausgeber gebunden. Eine veränderte Datei verliert die Regel automatisch.'; heading.append(eyebrow, title, explanation); const entry = document.createElement('div'); entry.className = 'allow-entry'; const input = document.createElement('input'); input.id = 'allowPath'; input.type = 'text'; input.spellcheck = false; input.placeholder = 'C:\\Program Files\\Hersteller\\Anwendung.exe'; const button = document.createElement('button'); button.id = 'allowApplication'; button.className = 'primary'; button.textContent = 'Verifizieren & freigeben'; entry.append(input, button); const list = document.createElement('div'); list.id = 'allowedApplications'; list.className = 'allow-list'; panel.append(heading, entry, list); modes.insertAdjacentElement('afterend', panel); button.addEventListener('click', async () => { const path = input.value.trim(); if (!path) return; try { await setApplication('Add', path); input.value = ''; } catch (error) { handleError(error); } }); }
function renderApplications(entries) { const nodes = asArray(entries).map(entry => { const row = document.createElement('div'); row.className = 'allow-item'; const info = document.createElement('div'); const title = document.createElement('strong'); const detail = document.createElement('small'); title.textContent = entry.path; detail.textContent = `${entry.signer} · SHA-256 ${String(entry.sha256 || '').slice(0, 16)}…`; info.append(title, detail); const remove = document.createElement('button'); remove.className = 'quiet'; remove.textContent = 'Entfernen'; remove.addEventListener('click', () => setApplication('Remove', entry.path).catch(handleError)); row.append(info, remove); return row; }); if (!nodes.length) { const empty = document.createElement('p'); empty.textContent = 'Keine zusätzlichen Anwendungen freigegeben.'; nodes.push(empty); } id('allowedApplications').replaceChildren(...nodes); }
function renderMhx(status, analyses, applications) { const mode = String(status.protectionMode || '').toLowerCase(); const intelligence = status.threatIntelligence || {}; setText('mhxRealtime', status.realtime ? 'AKTIV' : 'GESTÖRT'); setText('mhxMode', mode ? mode.toUpperCase() : '---'); setText('mhxBlocked', status.eventsBlocked || 0); setText('mhxIndicators', intelligence.indicators || 0); document.querySelectorAll('[data-mhx-mode]').forEach(button => { const active = button.dataset.mhxMode === mode; button.classList.toggle('mode-active', active); button.disabled = active; button.textContent = active ? 'AKTIV' : `${button.dataset.mhxMode[0].toUpperCase()}${button.dataset.mhxMode.slice(1)} aktivieren`; }); renderApplications(applications); const rows = asArray(analyses).map(item => { const row = document.createElement('tr'); row.append(statusCell(item.initialSeverity), statusCell(item.effectiveSeverity)); const context = document.createElement('td'); context.textContent = item.classification; const purpose = document.createElement('td'); purpose.textContent = [item.identifiedComponent, item.purpose].filter(Boolean).join(' · ') || item.detection; const parent = document.createElement('td'); parent.textContent = item.parent || '—'; const confidence = document.createElement('td'); confidence.textContent = `${(Number(item.confidenceBasisPoints) / 100).toFixed(1)} %`; row.append(context, purpose, parent, confidence); row.title = `${item.detection}\n${asArray(item.signals).join(', ')}`; return row; }); if (!rows.length) { const row = document.createElement('tr'); const cell = document.createElement('td'); cell.colSpan = 6; cell.textContent = status.realtime ? 'Noch keine relevanten Realtime-Ereignisse.' : 'Telemetrie ist gestört; automatische Wiederherstellung läuft.'; row.append(cell); rows.push(row); } id('mhxAnalyses').replaceChildren(...rows); }
async function loadMhx() { const [status, analyses, applications] = await Promise.all([api('/api/v1/mhx/status'), api('/api/v1/mhx/analyses'), api('/api/v1/mhx/applications')]); renderMhx(status, analyses, applications); }
async function setApplication(action, path) { const entries = await api('/api/v1/mhx/applications', { method: 'POST', json: { action, path } }); renderApplications(entries); toast(action === 'Add' ? 'Signierte Anwendung offiziell freigegeben.' : 'Anwendungsfreigabe entfernt.', 'good'); }
function formatBytes(value) { const bytes = Number(value || 0); if (bytes < 1024) return `${bytes} B`; const units = ['KiB', 'MiB', 'GiB', 'TiB']; let size = bytes; let unit = -1; do { size /= 1024; unit++; } while (size >= 1024 && unit < units.length - 1); return `${size.toFixed(size >= 100 ? 0 : 1)} ${units[unit]}`; }
function renderIntegrity(status, changes) { integrityStatus = status; const states = { DISABLED: 'DEAKTIVIERT', SCHEDULED: 'GEPLANT', SCANNING: 'SCANNT', BASELINE_CREATED: 'BASELINE ERSTELLT', VERIFIED: 'VERIFIZIERT', FAILED: 'FEHLER' }; setText('integrityState', states[status.state] || status.state || '---'); setText('integrityFiles', Number(status.filesHashed || 0).toLocaleString('de-DE')); setText('integrityBytes', formatBytes(status.bytesHashed)); setText('integrityErrors', Number(status.readErrors || 0).toLocaleString('de-DE')); setText('integrityAdded', status.added || 0); setText('integrityModified', status.modified || 0); setText('integrityDeleted', status.deleted || 0); setText('integrityGeneration', status.generation ? String(status.generation).slice(0, 18) : '---'); id('integrityInterval').value = String(status.intervalHours || 24); id('integrityToggle').textContent = status.enabled ? 'Überwachung deaktivieren' : 'Überwachung aktivieren'; id('integrityToggle').classList.toggle('mode-active', Boolean(status.enabled)); id('integrityScan').disabled = Boolean(status.running); id('integrityScan').textContent = status.running ? 'SCAN LÄUFT…' : 'Jetzt vollständig scannen'; const discovered = Number(status.filesDiscovered || 0); const hashed = Number(status.filesHashed || 0); const progress = discovered > 0 ? Math.min(100, Math.round((hashed / discovered) * 100)) : 0; id('integrityProgressBar').style.width = `${progress}%`; setText('integrityProgressText', status.running ? `${hashed.toLocaleString('de-DE')} von ${discovered.toLocaleString('de-DE')} entdeckten Dateien gehasht` : status.lastScanUtc ? `${hashed.toLocaleString('de-DE')} Dateien in Generation ${String(status.generation).slice(0, 18)}` : 'Noch keine Baseline vorhanden.'); setText('integritySchedule', status.enabled && status.nextScanUtc ? `Nächster automatischer Lauf: ${new Date(status.nextScanUtc).toLocaleString('de-DE')} · Intervall ${status.intervalHours} Stunden` : 'Überwachung ist deaktiviert.'); const rows = asArray(changes).map(change => { const row = document.createElement('tr'); row.append(statusCell(change.kind)); for (const value of [change.path, change.oldSha256 || '—', change.newSha256 || '—', formatBytes(change.size)]) { const cell = document.createElement('td'); cell.textContent = String(value); row.append(cell); } return row; }); if (!rows.length) { const row = document.createElement('tr'); const cell = document.createElement('td'); cell.colSpan = 5; cell.textContent = status.generation ? 'Keine Änderungen gegenüber der vorherigen Generation.' : 'Noch kein Vergleichslauf vorhanden.'; row.append(cell); rows.push(row); } id('integrityChanges').replaceChildren(...rows); }
async function loadIntegrity() { const status = await api('/api/v1/integrity/status'); const changes = status.running ? [] : await api('/api/v1/integrity/changes?limit=1000&offset=0'); renderIntegrity(status, changes); }
async function configureIntegrity(enabled) { const intervalHours = Number(id('integrityInterval').value); const status = await api('/api/v1/integrity/configuration', { method: 'POST', json: { enabled, intervalHours } }); renderIntegrity(status, []); toast(enabled ? `Integritätsüberwachung im ${intervalHours}-Stunden-Zyklus aktiviert.` : 'Integritätsüberwachung deaktiviert.', 'good'); }
async function startIntegrityScan() { const button = id('integrityScan'); button.disabled = true; await api('/api/v1/integrity/scan', { method: 'POST', json: {} }); toast('Vollständiger SHA-256-Scan aller festen Laufwerke gestartet.', 'good'); await loadIntegrity(); }
function renderHardening(components) { const entries = asArray(components); const active = entries.filter(component => component.active).length; const reboot = entries.filter(component => !component.active && component.rebootRequired).length; setText('hardeningActive', active); setText('hardeningMissing', entries.length - active); setText('hardeningReboot', reboot); setText('hardeningCoverage', entries.length ? `${Math.round((active / entries.length) * 100)}%` : '0%'); const cards = entries.map(component => { const card = document.createElement('article'); card.className = `panel component-card ${component.active ? 'component-active' : 'component-missing'}`; const head = document.createElement('div'); const category = document.createElement('span'); const state = document.createElement('b'); category.textContent = component.category; state.className = `state ${component.active ? 'pass' : 'warning'}`; state.textContent = component.active ? 'AKTIV' : 'FEHLT'; head.append(category, state); const title = document.createElement('h3'); title.textContent = component.name; const description = document.createElement('p'); description.textContent = component.description; const footer = document.createElement('div'); const rebootNote = document.createElement('small'); rebootNote.textContent = component.rebootRequired && !component.active ? 'Neustart zur Aktivierung erforderlich' : 'Live verifiziert'; const button = document.createElement('button'); button.className = component.active ? 'quiet mode-active' : 'primary'; button.disabled = Boolean(component.active); button.textContent = component.active ? 'GESCHÜTZT' : 'Einzeln härten'; button.addEventListener('click', () => enforceHardeningComponent(component.id, button).catch(handleError)); footer.append(rebootNote, button); card.append(head, title, description, footer); return card; }); id('hardeningComponents').replaceChildren(...cards); }
async function loadHardening() { renderHardening(await api('/api/v1/hardening/components')); }
async function enforceHardeningComponent(componentID, button) { const phrase = 'KOMPONENTE AKTIVIEREN'; if (globalThis.prompt(`Diese Windows-Schutzrichtlinie wird systemweit gesetzt. Zur Bestätigung exakt eingeben: ${phrase}`) !== phrase) return; button.disabled = true; button.textContent = 'WIRD VERIFIZIERT…'; const components = await api('/api/v1/hardening/components', { method: 'POST', json: { id: componentID } }); renderHardening(components); await refresh(); toast(`${componentID} wurde angewendet und neu gemessen.`, 'good'); }
async function loadEvidence() { const records = asArray(await api('/api/v1/evidence')); const rows = records.slice().reverse().map(record => { const row = document.createElement('tr'); for (const value of [record.sequence, new Date(record.timestamp).toLocaleString('de-DE'), record.kind, record.action, record.result]) { const cell = document.createElement('td'); cell.textContent = String(value); row.append(cell); } return row; }); if (!rows.length) { const row = document.createElement('tr'); const cell = document.createElement('td'); cell.colSpan = 5; cell.textContent = 'Noch keine Sicherheitstransaktionen aufgezeichnet.'; row.append(cell); rows.push(row); } id('events').replaceChildren(...rows); }
async function applyProfile(profile) { const phrase = profile === 'Isolation' ? 'ISOLATION AKTIVIEREN' : 'HÄRTUNG ANWENDEN'; if (globalThis.prompt(`Zur Bestätigung exakt eingeben: ${phrase}`) !== phrase) { toast('Transaktion wurde nicht bestätigt.'); return; } toast('VGT prüft und setzt das Profil. Dies kann mehrere Minuten dauern.'); await api('/api/v1/hardening/enforce', { method: 'POST', json: { profile } }); await Promise.all([refresh(), loadHardening()]); toast('Profil angewendet und verifiziert.', 'good'); }
function handleError(error) { const message = error instanceof Error ? error.message : 'Operation fehlgeschlagen'; toast(message, 'bad'); if (message.includes('authorization')) id('authDialog').showModal(); }
document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => { globalThis.scrollTo({ top: 0, behavior: 'auto' }); activate(button.dataset.view); }));
document.querySelectorAll('[data-profile]').forEach(button => button.addEventListener('click', () => applyProfile(button.dataset.profile).catch(handleError)));
async function runAudit() { const button = id('runAudit'); if (button.disabled) return; button.disabled = true; button.textContent = 'Audit läuft…'; try { toast('SafetySys Audit läuft.'); renderAudit(await api('/api/v1/audit/run', { method: 'POST', json: {} })); toast('Audit abgeschlossen.', 'good'); } finally { button.disabled = false; button.textContent = 'Erneut scannen'; } }
id('runAudit').addEventListener('click', () => runAudit().catch(handleError));
id('runXdr').addEventListener('click', async () => { try { toast('MHX XDR korreliert lokale Telemetrie.'); renderXdr(await api('/api/v1/xdr/scan', { method: 'POST', json: {} })); toast('XDR-Scan abgeschlossen.', 'good'); } catch (error) { handleError(error); } });
id('syncFeeds').addEventListener('click', async () => { try { toast('Threat-Intelligence wird validiert und atomar ausgerollt.'); await api('/api/v1/mhx/feeds/sync', { method: 'POST', json: {} }); await loadMhx(); toast('Threat-Intelligence und Firewall-Regeln sind aktuell.', 'good'); } catch (error) { handleError(error); } });
id('integrityToggle').addEventListener('click', () => configureIntegrity(!(integrityStatus && integrityStatus.enabled)).catch(handleError));
id('integrityInterval').addEventListener('change', () => { if (integrityStatus?.enabled) configureIntegrity(true).catch(handleError); });
id('integrityScan').addEventListener('click', () => startIntegrityScan().catch(handleError));
id('refreshHardening').addEventListener('click', () => loadHardening().catch(handleError));
document.querySelectorAll('[data-mhx-mode]').forEach(button => button.addEventListener('click', async () => { const mode = button.dataset.mhxMode; let confirmation = ''; if (mode === 'sovereign') { confirmation = globalThis.prompt('Sovereign blockiert ausgehenden Verkehr standardmäßig. Zur Bestätigung exakt eingeben: SOVEREIGN DEFAULT DENY') || ''; if (confirmation !== 'SOVEREIGN DEFAULT DENY') return; } const buttons = [...document.querySelectorAll('[data-mhx-mode]')]; buttons.forEach(item => { item.disabled = true; }); const previous = button.textContent; button.textContent = 'WIRD VERIFIZIERT…'; try { toast('MHX setzt und verifiziert die Windows-Schutzrichtlinie.'); const status = await api('/api/v1/mhx/mode', { method: 'POST', json: { mode, confirmation } }); await refresh(); const analyses = await api('/api/v1/mhx/analyses'); const applications = await api('/api/v1/mhx/applications'); renderMhx(status, analyses, applications); toast(`MHX-Modus ${mode.toUpperCase()} ist aktiv.`, 'good'); } catch (error) { button.textContent = previous; buttons.forEach(item => { item.disabled = false; }); handleError(error); } }));
id('auth').addEventListener('click', () => id('authDialog').showModal());
id('connect').addEventListener('click', event => { event.preventDefault(); const value = id('token').value.trim(); if (!value) return; token = value; id('token').value = ''; refresh().then(() => { id('authDialog').close(); toast('Operator-Sitzung authentifiziert.', 'good'); }).catch(handleError); });
id('verify').addEventListener('click', () => api('/api/v1/evidence/verify', { method: 'POST', json: {} }).then(() => toast('Beweiskette ist kryptografisch gültig.', 'good')).catch(handleError));
id('rollback').addEventListener('click', async () => { if (globalThis.prompt('Zur Bestätigung exakt eingeben: BASELINE WIEDERHERSTELLEN') !== 'BASELINE WIEDERHERSTELLEN') return; try { await api('/api/v1/hardening/rollback', { method: 'POST', json: {} }); await refresh(); toast('Gesicherter Vorzustand wurde wiederhergestellt.', 'good'); } catch (error) { handleError(error); } });
globalThis.setInterval(() => setText('clock', new Date().toLocaleTimeString('de-DE')), 1000);
globalThis.setInterval(() => { const page = document.querySelector('[data-page="integrity"]'); if (page && !page.hidden) loadIntegrity().catch(handleError); }, 3000);
globalThis.setInterval(async () => { if (document.hidden || backgroundRefreshRunning) return; const active = document.querySelector('.nav.active')?.dataset.view; if (!active || active === 'integrity' || active === 'audit') return; backgroundRefreshTick++; backgroundRefreshRunning = true; try { if (active === 'xdr') await loadMhx(); else if (active === 'overview') await refresh(); else if (active === 'hardening' && backgroundRefreshTick % 6 === 0) await loadHardening(); } catch {} finally { backgroundRefreshRunning = false; } }, 5000);
const fragment = new URLSearchParams(location.hash.slice(1));
mountSovereignAllowUI();
if (fragment.has('bootstrap')) { const bootstrap = fragment.get('bootstrap').trim(); history.replaceState(null, '', location.pathname); exchangeBootstrap(bootstrap).then(refresh).catch(handleError); } else { id('authDialog').showModal(); }
activate(location.hash.slice(1));
